"""Run every query in sql/ against the CSV and write the results to results/query_results.md."""
from pathlib import Path
import re
import duckdb

ROOT = Path(__file__).resolve().parents[1]
con = duckdb.connect()
out = ["# Query results\n", "_Generated by `scripts/run_queries.py` with DuckDB._\n"]

for sql_file in sorted((ROOT / "sql").glob("*.sql")):
    text = sql_file.read_text()
    # Split on question headers; the first chunk may hold setup statements
    parts = re.split(r"(?m)^-- (Q\d*:.*)$", text)
    con.execute(parts[0].replace("data/", str(ROOT / "data") + "/"))
    for title, body in zip(parts[1::2], parts[2::2]):
        df = con.execute(body.replace("data/", str(ROOT / "data") + "/")).df()
        out += [f"\n## {title.strip()}\n", f"_Source: `sql/{sql_file.name}`_\n\n", df.to_markdown(index=False), "\n"]

(ROOT / "results").mkdir(exist_ok=True)
(ROOT / "results" / "query_results.md").write_text("\n".join(out))
print("Wrote results/query_results.md")
